[package]
name = "p9_scene_tool"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2018"


[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
grim = { path = "../grim" }
thiserror = "1.0.30"