[package]
name = "scene_tool"
version = "0.1.0"
authors = ["PikminGuts92"]
edition = "2021"

[dependencies]
clap = { version = "3.2.12", features = ["derive"] }
grim = { path = "../grim" }
thiserror = "1.0.31"
