[package]
name = "scene_tool"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
grim = { workspace = true, features = [ "midi", "model" ] }
thiserror = { workspace = true }
