[package]
name = "anim_preview"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
grim = { workspace = true }
keyframe = "1.1.1"
nalgebra = "0.32.3"
rerun = { version = "0.7.0", features = [ "native_viewer" ] }
shared = { path = "../shared" }