[package]
name = "grim_midi"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
midly = { version = "0.5.3" }

[dev-dependencies]
rstest = "0.18.2"

[lints]
workspace = true